metadata = (
  ? uas: uas-datum,
  ? utm: utm-datum,
  * &(tstr, int): any
)

uas-datum = #6.ASDAM({
  0: [null, TBD3, null] / null,
  + &(uas-datum-ctx) => any
})

utm-datum = [
  operational_intent: uuid,
  uss_uri: uri
]