; DRIP Type Definitions 
x509 = bstr ; DER encoded X.509 object (CSR or Certificate)
endorsement = bstr .size 136
hash = bstr .size 8 ; generated with cSHAKE
auth-data = bstr .size 1..362
uas-id = bstr .size 20
utc = tdate / time
entity-type = uint / tstr
uas-datum-ctx = 1..18 / tstr
nibble-field = 0..15

; Common External Tags
uuid = #6.37(bstr)
ip6 = #6.54(bstr)
position = #6.103([
	latitude: number, 
	longitude: number, 
	altitude: number
])