inquiry = [
  entities: { &(entity-id) => entity },
  metadata: map / null
]
entity = [
  hhit_entity_type: uint,
  keys: { &(key-id): key },
  metadata: map / null
]
key = [
  csr: bytes / text .b64u bytes,
  metadata: map / null
]