inquiry = [
  entities: { &(entity-id): entity },
  options: aviation-map,
  metadata: aviation-map
]
entity = [
  entity_type: entity-type,
  keys: { &(key-id): key },
  options: aviation-map,
  metadata: aviation-map
]
key = [
  csr: x509,
  options: aviation-map,
  metadata: aviation-map
]