response = [
  success: { &(entity-id): success-data } / null
  failure: [ + error-data ] / null
  shared: map / null
]
success-data = [
  keys: { &(key-id): map },
  shared: map / null
]
error-data = [
  eid: &(entity-id) / null,
  kid: &(key-id) / null,
  cat: any,
  msg: any
]