response = [
  success: [
    entities: { &(entity-id): success-data },
    shared: map
  ] / null,
  failure: [ + error-data ] / null
]
success-data = [
  keys: { &(key-id): map },
  shared: map
]
error-data = [
  eid: &(entity-id) / null,
  kid: &(key-id) / null,
  cat: any,
  msg: any
]