uas = {
  uas_type => nibble-field,
  uas_ids => [ + [
    type: nibble-field,
    id: uas-id
  ]],
  ? auths => [ + [
    type: nibble-field,
    data: auth-data
  ]],
  ? self_id => [
    type: uint .size(1),
    description: tstr .size(23)
  ],
  ? classification => [
    class_type: 0..8,
    class: nibble-field,
    category: nibble-field
  ]
  ? area => [
    count: 1..255,
    radius: number,
    floor: number,
    ceiling: number
  ],
  ? operator_id => [
    type: uint .size(1),
    id: bstr .size(20)
  ],
  ? ua_status => nibble-field,
  ? track_dir => 0..361,
  ? ua_position => [
    lla: position,
    pressure_altitude: number
  ],
  ? ua_height => [
    is_agl: bool,
    height: number
  ],
  ? ua_speed => [
    vertical: number,
    horizontal: number
  ],
  ? ae_positions => [ + [
    source: 0..3,
    lla: position
  ]],
  ? uas_time => utc
}
